account/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as django_auth_views

app_name = 'account'

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", django_auth_views.LogoutView.as_view(), name="logout"),
    path("", views.start_page, name="home"),
]

event/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path("", views.Events.as_view(), name="events_list"),
]

events_memorizer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from account import urls as account_urls
from event import urls as events_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('', include(account_urls, namespace='account')),
    path('events/', include(events_urls, namespace='events')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

account/models.py
from django.db import models

# Create your models here.

event/models.py
from django.contrib.auth.models import User
from django.db import models

from django.utils.translation import gettext_lazy as _


# Create your models here.

class Event(models.Model):
    """User event model.

    Attributes:
        owner (Manager): Foreign key User that created this event.
        title (str): Event title.
        place (bool): Location of the event.
        description (set): Event description.

    """
    owner = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='own_events',
        verbose_name=_('Owner'),
    )

    title = models.CharField(
        max_length=100,
        verbose_name=_('Title')
    )

    place = models.CharField(
        max_length=250,
        verbose_name=_('Place'),
    )

    description = models.TextField(
        verbose_name=_('Description'),
    )

event/forms.py
from django import forms

from .models import Event
from .widgets import MapWidget


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('title', 'place', 'description')
        widgets = {
            'place': MapWidget(map_attrs={"center": [92.85656693081211, 56.01433428426304],}),
        }
        labels = {
            'place': "Choose event's place",
        }

account/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.
def login(request):
    return render(request, 'login.html')


def start_page(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/events')
    return render(request, 'start_page.html')

event/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from django.views.generic.edit import FormMixin

from .models import Event
from .forms import EventForm


class Events(LoginRequiredMixin, FormMixin, ListView):
    model = Event
    context_object_name = 'events'
    template_name = 'events.html'
    success_url = '/events/'
    form_class = EventForm

    def post(self, request, *args, **kwargs):
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            sticker = form.save(commit=False)
            sticker.owner = request.user
            sticker.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        self.object_list = self.get_queryset()
        return super(Events, self).get_context_data(**kwargs)

    def get_queryset(self):
        return Event.objects.filter(owner=self.request.user)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <title>Events memorizer</title>
</head>
<body>
<script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg ">
                <a class="navbar-brand" href="/">Events Memorizer</a>
                <ul class="navbar-nav">
                     {% if request.user.is_authenticated %}
                         <li class="nav-item dropdown">
                             <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              {{ request.user.first_name }}
                             </a>
                              <div class="dropdown-menu" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="">Events</a>
                                  <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
                            </div>
                         </li>
                     {% else %}
                         <li class="nav-item">
                                <button class="btn btn-primary mb-2">
                                    <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
                                </button>
                         </li>
                     {% endif %}
                </ul>
        </nav>
        <div class="container-fluid">
                {% block content %}
                {% endblock %}
        </div>
    </div>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
{% block scripts %}{% endblock %}
</html>

templates/events.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Sign in {% endblock %}
{% block content %}
    {% load mapbox_location_field_tags %}
    {% location_field_includes %}

    {% for ass in backends.associated %}
      {% if ass.provider == 'facebook' %}
      <div class="row justify-content-md-center">
            <div class="col-md-6 text-center">
                <img src="{{ass.extra_data.picture.data.url}}" alt="" width="150" height="150" style="border-radius: 50%">
                <p> Name:  {{ ass.extra_data.name }} </p>
            </div>
      </div>
      {% endif %}
    {% endfor %}
    <div id="events" class="row text-center">
    {% if events %}
        {% for event in events %}
            <div id="{{ event.id }}" class="col-md-4 event text-center">
                <div class="col-12 title"><p> {{ event.title }} </p></div>
                <div class="col-12 place"><p> {{ event.place }} </p></div>
                <div class="col-12 description"><p> {{ event.description }} </p></div>
            </div>
        {% endfor %}
        <div class="row-md-4 event col-md-4 justify-content-center">
            <button id="add_new_event" type="submit" class="btn btn-primary col-3  d-block">+</button>
        </div>
    {% else %}
        <div class="col-md-12"><h2>У вас нет ни одного воспоминания</h2></div>
        <div class="col-md-12 justify-content-md-center">
            <button id="add_new_event" type="submit" class="btn btn-primary">Добавить воспоминание</button>
        </div>
    {% endif %}
    </div>
    <div id="form_div">
        <form enctype="multipart/form-data" method="post">
                {{ form.title|as_crispy_field }}
                {{ form.place.label }}
                <p id="place_error_p" class="text-primary">
                    We cannot get geolocation using a map, sorry. You can simply enter the place yourself.
                    Or try place mark again.
                </p>
                {{ form.place }}
                {{ form.description|as_crispy_field }}
                {{ form.media }}
                {% csrf_token %}
                <p id="button_inf_p" class="text-primary">Wait please, we are waiting for your event place</p>
                <button id="submit_add_event" type="submit" name="add_event" class="btn btn-primary">Add event</button>
        </form>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/form.js' %}"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %} Sign in {% endblock %}
{% block content %}
    <h2>You are unauthorized</h2>
    <p>You must login with facebook</p>
{% endblock %}

templates/start_page.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
<h2>Events Memorizer</h2>
    <p>Here you can store your memories. Just log in and save the memories of the events,
        the place of these events and the description.</p>
{% endblock %}